version: '4.0'

services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: app
    networks:
      - backend-network
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  app:
    build: .
    depends_on:
    - database
    container_name: app
    environment:
      DATABASE_URL: postgresql://teste:teste123@database:5432/app?schema=public
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
    ports:
      - 3000:3000
    networks:
      - backend-network



networks:
  backend-network:
    driver: bridge